AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb


