# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/idle_game_resources', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # IdleGameResource. As you add validations to IdleGameResource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  let!(:user) { create(:user, role: 'ADMIN') }

  before do
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      IdleGameResource.create! valid_attributes
      get admin_idle_game_resources_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      idle_game_resource = IdleGameResource.create! valid_attributes
      get admin_idle_game_resource_url(idle_game_resource)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_admin_idle_game_resource_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      idle_game_resource = IdleGameResource.create! valid_attributes
      get edit_admin_idle_game_resource_url(idle_game_resource)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new IdleGameResource' do
        expect do
          post admin_idle_game_resources_url, params: { idle_game_resource: valid_attributes }
        end.to change(IdleGameResource, :count).by(1)
      end

      it 'redirects to the created idle_game_resource' do
        post admin_idle_game_resources_url, params: { idle_game_resource: valid_attributes }
        expect(response).to redirect_to(admin_idle_game_resource_url(IdleGameResource.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new IdleGameResource' do
        expect do
          post admin_idle_game_resources_url, params: { idle_game_resource: invalid_attributes }
        end.to change(IdleGameResource, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admin_idle_game_resources_url, params: { idle_game_resource: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested idle_game_resource' do
        idle_game_resource = IdleGameResource.create! valid_attributes
        patch admin_idle_game_resource_url(idle_game_resource), params: { idle_game_resource: new_attributes }
        idle_game_resource.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the idle_game_resource' do
        idle_game_resource = IdleGameResource.create! valid_attributes
        patch admin_idle_game_resource_url(idle_game_resource), params: { idle_game_resource: new_attributes }
        idle_game_resource.reload
        expect(response).to redirect_to(idle_game_resource_url(idle_game_resource))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        idle_game_resource = IdleGameResource.create! valid_attributes
        patch admin_idle_game_resource_url(idle_game_resource), params: { idle_game_resource: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested idle_game_resource' do
      idle_game_resource = IdleGameResource.create! valid_attributes
      expect do
        delete admin_idle_game_resource_url(idle_game_resource)
      end.to change(IdleGameResource, :count).by(-1)
    end

    it 'redirects to the idle_game_resources list' do
      idle_game_resource = IdleGameResource.create! valid_attributes
      delete admin_idle_game_resource_url(idle_game_resource)
      expect(response).to redirect_to(admin_idle_game_resources_url)
    end
  end
end
