# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/resources', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Resource. As you add validations to Resource, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      key: 'my-string',
      name: 'MyString'
    }
  end

  let(:invalid_attributes) do
    {
      name: nil
    }
  end

  let!(:user) { create(:user, role: 'ADMIN') }

  before do
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Resource.create! valid_attributes
      get admin_resources_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      resource = Resource.create! valid_attributes
      get admin_resource_url(resource)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_admin_resource_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      resource = Resource.create! valid_attributes
      get edit_admin_resource_url(resource)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Resource' do
        expect do
          post admin_resources_url, params: { resource: valid_attributes }
        end.to change(Resource, :count).by(1)
      end

      it 'redirects to the created resource' do
        post admin_resources_url, params: { resource: valid_attributes }
        expect(response).to redirect_to(admin_resource_url(Resource.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Resource' do
        expect do
          post admin_resources_url, params: { resource: invalid_attributes }
        end.to change(Resource, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admin_resources_url, params: { resource: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          name: 'New Name'
        }
      end

      it 'updates the requested resource' do
        resource = Resource.create! valid_attributes
        patch admin_resource_url(resource), params: { resource: new_attributes }
        resource.reload
        expect(resource.name).to eq('New Name')
      end

      it 'redirects to the resource' do
        resource = Resource.create! valid_attributes
        patch admin_resource_url(resource), params: { resource: new_attributes }
        resource.reload
        expect(response).to redirect_to(admin_resource_url(resource))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        resource = Resource.create! valid_attributes
        patch admin_resource_url(resource), params: { resource: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested resource' do
      resource = Resource.create! valid_attributes
      expect do
        delete admin_resource_url(resource)
      end.to change(Resource, :count).by(-1)
    end

    it 'redirects to the resources list' do
      resource = Resource.create! valid_attributes
      delete admin_resource_url(resource)
      expect(response).to redirect_to(admin_resources_url)
    end
  end
end
