# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/seasons', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Season. As you add validations to Season, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      name: 'MyString',
      speed: 1,
      active: false
    }
  end

  let(:invalid_attributes) do
    {
      name: nil,
      speed: nil,
      active: false
    }
  end

  let!(:user) { create(:user, role: 'ADMIN') }

  before do
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Season.create! valid_attributes
      get admin_seasons_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      season = Season.create! valid_attributes
      get admin_season_url(season)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_admin_season_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      season = Season.create! valid_attributes
      get edit_admin_season_url(season)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Season' do
        expect do
          post admin_seasons_url, params: { season: valid_attributes }
        end.to change(Season, :count).by(1)
      end

      it 'redirects to the created season' do
        post admin_seasons_url, params: { season: valid_attributes }
        expect(response).to redirect_to(admin_season_url(Season.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Season' do
        expect do
          post admin_seasons_url, params: { season: invalid_attributes }
        end.to change(Season, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admin_seasons_url, params: { season: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          name: 'MyString 2'
        }
      end

      it 'updates the requested season' do
        season = Season.create! valid_attributes
        patch admin_season_url(season), params: { season: new_attributes }
        season.reload

        expect(season.name).to eq('MyString 2')
      end

      it 'redirects to the season' do
        season = Season.create! valid_attributes
        patch admin_season_url(season), params: { season: new_attributes }
        season.reload
        expect(response).to redirect_to(admin_season_url(season))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        season = Season.create! valid_attributes
        patch admin_season_url(season), params: { season: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested season' do
      season = Season.create! valid_attributes
      expect do
        delete admin_season_url(season)
      end.to change(Season, :count).by(-1)
    end

    it 'redirects to the seasons list' do
      season = Season.create! valid_attributes
      delete admin_season_url(season)
      expect(response).to redirect_to(admin_seasons_url)
    end
  end
end
