# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/structures', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Structure. As you add validations to Structure, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      name: 'MyString'
    }
  end

  let(:invalid_attributes) do
    {
      name: nil
    }
  end

  let!(:user) { create(:user, role: 'ADMIN') }

  before do
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Structure.create! valid_attributes
      get admin_structures_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      structure = Structure.create! valid_attributes
      get admin_structure_url(structure)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_admin_structure_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      structure = Structure.create! valid_attributes
      get edit_admin_structure_url(structure)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Structure' do
        expect do
          post admin_structures_url, params: { structure: valid_attributes }
        end.to change(Structure, :count).by(1)
      end

      it 'redirects to the created structure' do
        post admin_structures_url, params: { structure: valid_attributes }
        expect(response).to redirect_to(admin_structure_url(Structure.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Structure' do
        expect do
          post admin_structures_url, params: { structure: invalid_attributes }
        end.to change(Structure, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admin_structures_url, params: { structure: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          name: 'NewName'
        }
      end

      it 'updates the requested structure' do
        structure = Structure.create! valid_attributes
        patch admin_structure_url(structure), params: { structure: new_attributes }
        structure.reload
        expect(structure.name).to eq('NewName')
      end

      it 'redirects to the structure' do
        structure = Structure.create! valid_attributes
        patch admin_structure_url(structure), params: { structure: new_attributes }
        structure.reload
        expect(response).to redirect_to(admin_structure_url(structure))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        structure = Structure.create! valid_attributes
        patch admin_structure_url(structure), params: { structure: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested structure' do
      structure = Structure.create! valid_attributes
      expect do
        delete admin_structure_url(structure)
      end.to change(Structure, :count).by(-1)
    end

    it 'redirects to the structures list' do
      structure = Structure.create! valid_attributes
      delete admin_structure_url(structure)
      expect(response).to redirect_to(admin_structures_url)
    end
  end
end
