# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/structure_level_details', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # StructureLevelDetail. As you add validations to StructureLevelDetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      structure_id: structure.id,
      level: 1,
      description: 'MyString'
    }
  end

  let(:invalid_attributes) do
    {
      structure: nil,
      level: nil,
      description: nil
    }
  end

  let!(:user) { create(:user, role: 'ADMIN') }
  let!(:structure) { create(:structure) }

  before do
    sign_in user
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      StructureLevelDetail.create! valid_attributes
      get admin_structure_level_details_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      structure_level_detail = StructureLevelDetail.create! valid_attributes
      get admin_structure_level_detail_url(structure_level_detail)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_admin_structure_level_detail_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      structure_level_detail = StructureLevelDetail.create! valid_attributes
      get edit_admin_structure_level_detail_url(structure_level_detail)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new StructureLevelDetail' do
        expect do
          post admin_structure_level_details_url, params: { structure_level_detail: valid_attributes }
        end.to change(StructureLevelDetail, :count).by(1)
      end

      it 'redirects to the created structure_level_detail' do
        post admin_structure_level_details_url, params: { structure_level_detail: valid_attributes }
        expect(response).to redirect_to(admin_structure_level_detail_url(StructureLevelDetail.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new StructureLevelDetail' do
        expect do
          post admin_structure_level_details_url, params: { structure_level_detail: invalid_attributes }
        end.to change(StructureLevelDetail, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admin_structure_level_details_url, params: { structure_level_detail: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          description: 'test 2'
        }
      end

      it 'updates the requested structure_level_detail' do
        structure_level_detail = StructureLevelDetail.create! valid_attributes
        patch admin_structure_level_detail_url(structure_level_detail), params: { structure_level_detail: new_attributes }
        structure_level_detail.reload
        expect(structure_level_detail.description).to eq('test 2')
      end

      it 'redirects to the structure_level_detail' do
        structure_level_detail = StructureLevelDetail.create! valid_attributes
        patch admin_structure_level_detail_url(structure_level_detail), params: { structure_level_detail: new_attributes }
        structure_level_detail.reload
        expect(response).to redirect_to(admin_structure_level_detail_url(structure_level_detail))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        structure_level_detail = StructureLevelDetail.create! valid_attributes
        patch admin_structure_level_detail_url(structure_level_detail), params: { structure_level_detail: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested structure_level_detail' do
      structure_level_detail = StructureLevelDetail.create! valid_attributes
      expect do
        delete admin_structure_level_detail_url(structure_level_detail)
      end.to change(StructureLevelDetail, :count).by(-1)
    end

    it 'redirects to the structure_level_details list' do
      structure_level_detail = StructureLevelDetail.create! valid_attributes
      delete admin_structure_level_detail_url(structure_level_detail)
      expect(response).to redirect_to(admin_structure_level_details_url)
    end
  end
end
